title:   Chris Choi
logo: "/images/hasta.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  Results-driven data analyst. Proficient in Excel, SQL, Python, Power BI, and Tableau. Skilled in analyzing behavioral data, identifying business gaps, and developing solutions that meet the needs of both internal and external stakeholders. Looking for more real world experience to expand my horizon.
  <br><br><br>
  <a href="https://www.linkedin.com/in/chris-sy-choi/">View My LinkedIn Profile</a>
  <br><br>
  <a href="https://www.bit.ly/chris-choi-portfolio">View My Tableau Work Samples</a>
  <br><br>
  
theme: jekyll-theme-minimal   
 
